// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: body_skeleton.proto
#ifndef GRPC_body_5fskeleton_2eproto__INCLUDED
#define GRPC_body_5fskeleton_2eproto__INCLUDED

#include "body_skeleton.pb.h"

#include <grpc++/support/async_stream.h>
#include <grpc++/impl/rpc_method.h>
#include <grpc++/impl/proto_utils.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/support/async_unary_call.h>
#include <grpc++/support/status.h>
#include <grpc++/support/stub_options.h>
#include <grpc++/support/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace bodyskeleton {

class BodySkeleton GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetUsers(::grpc::ClientContext* context, const ::bodyskeleton::User& request, ::bodyskeleton::User* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bodyskeleton::User>> AsyncGetUsers(::grpc::ClientContext* context, const ::bodyskeleton::User& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bodyskeleton::User>>(AsyncGetUsersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::bodyskeleton::Joint>> GetSkeleton(::grpc::ClientContext* context, const ::bodyskeleton::User& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::bodyskeleton::Joint>>(GetSkeletonRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::bodyskeleton::Joint>> AsyncGetSkeleton(::grpc::ClientContext* context, const ::bodyskeleton::User& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::bodyskeleton::Joint>>(AsyncGetSkeletonRaw(context, request, cq, tag));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bodyskeleton::User>* AsyncGetUsersRaw(::grpc::ClientContext* context, const ::bodyskeleton::User& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::bodyskeleton::Joint>* GetSkeletonRaw(::grpc::ClientContext* context, const ::bodyskeleton::User& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::bodyskeleton::Joint>* AsyncGetSkeletonRaw(::grpc::ClientContext* context, const ::bodyskeleton::User& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::Channel>& channel);
    ::grpc::Status GetUsers(::grpc::ClientContext* context, const ::bodyskeleton::User& request, ::bodyskeleton::User* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bodyskeleton::User>> AsyncGetUsers(::grpc::ClientContext* context, const ::bodyskeleton::User& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bodyskeleton::User>>(AsyncGetUsersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::bodyskeleton::Joint>> GetSkeleton(::grpc::ClientContext* context, const ::bodyskeleton::User& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::bodyskeleton::Joint>>(GetSkeletonRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::bodyskeleton::Joint>> AsyncGetSkeleton(::grpc::ClientContext* context, const ::bodyskeleton::User& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::bodyskeleton::Joint>>(AsyncGetSkeletonRaw(context, request, cq, tag));
    }

   private:
    std::shared_ptr< ::grpc::Channel> channel_;
    ::grpc::ClientAsyncResponseReader< ::bodyskeleton::User>* AsyncGetUsersRaw(::grpc::ClientContext* context, const ::bodyskeleton::User& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientReader< ::bodyskeleton::Joint>* GetSkeletonRaw(::grpc::ClientContext* context, const ::bodyskeleton::User& request) GRPC_OVERRIDE;
    ::grpc::ClientAsyncReader< ::bodyskeleton::Joint>* AsyncGetSkeletonRaw(::grpc::ClientContext* context, const ::bodyskeleton::User& request, ::grpc::CompletionQueue* cq, void* tag) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_GetUsers_;
    const ::grpc::RpcMethod rpcmethod_GetSkeleton_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::Channel>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::SynchronousService {
   public:
    Service() : service_(nullptr) {}
    virtual ~Service();
    virtual ::grpc::Status GetUsers(::grpc::ServerContext* context, const ::bodyskeleton::User* request, ::bodyskeleton::User* response);
    virtual ::grpc::Status GetSkeleton(::grpc::ServerContext* context, const ::bodyskeleton::User* request, ::grpc::ServerWriter< ::bodyskeleton::Joint>* writer);
    ::grpc::RpcService* service() GRPC_OVERRIDE GRPC_FINAL;
   private:
    ::grpc::RpcService* service_;
  };
  class AsyncService GRPC_FINAL : public ::grpc::AsynchronousService {
   public:
    explicit AsyncService();
    ~AsyncService() {};
    void RequestGetUsers(::grpc::ServerContext* context, ::bodyskeleton::User* request, ::grpc::ServerAsyncResponseWriter< ::bodyskeleton::User>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
    void RequestGetSkeleton(::grpc::ServerContext* context, ::bodyskeleton::User* request, ::grpc::ServerAsyncWriter< ::bodyskeleton::Joint>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
  };
};

}  // namespace bodyskeleton


#endif  // GRPC_body_5fskeleton_2eproto__INCLUDED
